### ISSUE TITLE
Block double weeks for lvl 5 to 7 creatures

### ISSUE THREAD

**Issue by by003** [vcmi-mods/new-pavilion#9]
When I play the game with pavillion mod, there are too many high level creatures in the map. However, it should not be allowed in H3 because of the power of diplomacy. 
We need to block this by changing the json of ammut, sphinx and anubis here.
"hasDoubleWeek": false,

**Comment by by003** [comment]
@misiokles this is my proposal, please check it.

**Comment by misiokles** [comment]
For Andruid's command only non-upgraded lvl1 and lvl2 creatures have double week paramter.
